import { jest } from '@jest/globals';
import { IntegrationLeastPrivilegeCheck } from '../../../../src/checks/impl/IntegrationLeastPrivilegeCheck.js';
import type { AuditContext } from '@cclabsnz/sf-core';

/** 15-char User id, the shape `recordVisibility` validates before interpolating it. */
const AUDIT_USER_ID = '005AUDIT00000AA';

interface Opts {
  users?: unknown[];
  usersThrow?: boolean;
  psa?: unknown[];
  psaThrow?: boolean;
  logins?: unknown[];
  loginsThrow?: boolean;
  objPerms?: unknown[];
  objPermsThrow?: boolean;
  writes?: Record<string, 'THROW' | { CreatedById?: unknown[]; LastModifiedById?: unknown[] }>;
  /** Identity of the running audit user, as `/chatter/users/me` answers it. */
  auditUser?: 'THROW' | 'NO_ID' | string;
  /** What the running audit user's own permission-set assignments say about record visibility. */
  auditUserSeesAllRecords?: boolean | 'THROW';
  /** Assignments of the granting permission sets held by users outside the integration set. */
  sharedAssignments?: unknown[] | 'THROW';
}

function makeCtx(opts: Opts): AuditContext {
  const queryAll = jest.fn() as any;
  queryAll.mockImplementation(async (soql: string) => {
    if (soql.includes('FROM PermissionSetAssignment')) {
      // The running audit user's own visibility, not the integration accounts' grants.
      if (/AssigneeId = '/.test(soql)) {
        if (opts.auditUserSeesAllRecords === 'THROW') throw new Error('no access');
        const sees = opts.auditUserSeesAllRecords ?? true;
        return [{ PermissionSet: { PermissionsViewAllData: sees, PermissionsModifyAllData: false } }];
      }
      if (soql.includes('GROUP BY PermissionSetId')) {
        if (opts.sharedAssignments === 'THROW') throw new Error('no access');
        return opts.sharedAssignments ?? [];
      }
      if (opts.psaThrow) throw new Error('no access');
      return opts.psa ?? [];
    }
    if (soql.includes('FROM LoginHistory')) {
      if (opts.loginsThrow) throw new Error('no access');
      return opts.logins ?? [];
    }
    if (soql.includes('FROM ObjectPermissions')) {
      if (opts.objPermsThrow) throw new Error('no access');
      return opts.objPerms ?? [];
    }
    const probe = /FROM (\w+) WHERE (CreatedById|LastModifiedById)/.exec(soql);
    if (probe) {
      const [, object, field] = probe;
      const forObject = (opts.writes ?? {})[object];
      if (forObject === 'THROW') throw new Error('not queryable');
      return (forObject as Record<string, unknown[]> | undefined)?.[field] ?? [];
    }
    if (soql.includes('FROM User')) {
      if (opts.usersThrow) throw new Error('no access');
      return opts.users ?? [];
    }
    return [];
  });
  const get = jest.fn() as any;
  get.mockImplementation(async () => {
    if (opts.auditUser === 'THROW') throw new Error('Chatter is disabled in this organization');
    if (opts.auditUser === 'NO_ID') return {};
    return { id: opts.auditUser ?? AUDIT_USER_ID };
  });
  return {
    soql: { query: jest.fn(), queryAll } as any,
    tooling: { query: jest.fn(), getRecord: jest.fn() } as any,
    rest: { get } as any,
    orgInfo: { id: 'o', name: 'n', type: 'DE', isSandbox: false, instance: 'NA1', instanceUrl: 'https://x' },
    cache: {},
  } as any;
}

const SVC = [{
  Id: '005a', Username: 'svc.api@acme.com',
  Profile: { Name: 'Integration', UserLicense: { Name: 'Salesforce' } },
  LastLoginDate: '2026-08-25T00:00:00.000Z', CreatedDate: '2020-01-01T00:00:00.000Z',
}];

// Seven verified fields only — PermissionsViewSetup and PermissionsManageProfilesPermissionsets
// were dropped per controller ruling R12 (unverified field names, not in permCatalog.ts or any
// shipping query).
const NO_PERMS = {
  PermissionsAuthorApex: false, PermissionsCustomizeApplication: false, PermissionsManageUsers: false,
  PermissionsAssignPermissionSets: false,
  PermissionsDataExport: false, PermissionsViewAllUsers: false,
  PermissionsPasswordNeverExpires: false,
};

const psa = (over: Record<string, unknown> = {}) => ({
  AssigneeId: '005a',
  PermissionSetId: '0PS1',
  PermissionSet: { Name: 'Integration PS', IsOwnedByProfile: false, ...NO_PERMS, ...over },
});

describe('IntegrationLeastPrivilegeCheck — structural findings', () => {
  const check = new IntegrationLeastPrivilegeCheck();

  it('reports Author Apex on an integration account as CRITICAL', async () => {
    const r = await check.run(makeCtx({ users: SVC, psa: [psa({ PermissionsAuthorApex: true })] }));
    const f = r.findings.find((x) => x.id === 'integration-least-privilege-escalation-permissions')!;
    expect(f.riskLevel).toBe('CRITICAL');
    expect(f.affectedItems![0].label).toContain('svc.api@acme.com');
    expect(f.affectedItems![0].note).toContain('Author Apex');
  });

  // A profile-owned permission set's Name is Salesforce's autogenerated internal string
  // (id-shaped, e.g. "X00e5w000001AbCd"), not the profile's label — naming that string in the
  // finding would tell a reader nothing. This is the CRITICAL escalation-permissions finding, the
  // highest-severity and most-read one this check emits, so it pins that the note names the
  // assignee's actual profile (from SVC's Profile.Name, 'Integration') instead.
  it('names the grant path using the assignee\'s profile name, not the autogenerated permission-set name, on the CRITICAL escalation finding', async () => {
    const r = await check.run(makeCtx({
      users: SVC,
      psa: [psa({ PermissionsAuthorApex: true, IsOwnedByProfile: true, Name: 'X00e5w000001AbCd' })],
    }));
    const f = r.findings.find((x) => x.id === 'integration-least-privilege-escalation-permissions')!;
    expect(f.riskLevel).toBe('CRITICAL');
    expect(f.affectedItems![0].note).toContain('via profile Integration');
    expect(f.affectedItems![0].note).not.toContain('X00e5w000001AbCd');
  });

  it('reports Data Export separately as HIGH, not as an escalation permission', async () => {
    const r = await check.run(makeCtx({ users: SVC, psa: [psa({ PermissionsDataExport: true })] }));
    expect(r.findings.map((f) => f.id)).toContain('integration-least-privilege-data-permissions');
    expect(r.findings.map((f) => f.id)).not.toContain('integration-least-privilege-escalation-permissions');
    expect(r.findings.find((f) => f.id === 'integration-least-privilege-data-permissions')!.riskLevel).toBe('HIGH');
  });

  it('reports Password Never Expires as MEDIUM hygiene', async () => {
    const r = await check.run(makeCtx({ users: SVC, psa: [psa({ PermissionsPasswordNeverExpires: true })] }));
    const f = r.findings.find((x) => x.id === 'integration-least-privilege-hygiene')!;
    expect(f.riskLevel).toBe('MEDIUM');
  });

  it('does not report Modify All Data, which integration-users owns', async () => {
    const r = await check.run(makeCtx({
      users: SVC,
      psa: [psa({ PermissionsModifyAllData: true } as Record<string, unknown>)],
    }));
    expect(r.findings.map((f) => f.id)).not.toContain('integration-least-privilege-escalation-permissions');
  });

  it('passes with -none when no integration accounts are resolved', async () => {
    const r = await check.run(makeCtx({ users: [] }));
    expect(r.findings.map((f) => f.id)).toEqual(['integration-least-privilege-none']);
    expect(r.findings[0].passed).toBe(true);
  });

  it('is inconclusive when users cannot be queried', async () => {
    const r = await check.run(makeCtx({ usersThrow: true }));
    expect(r.findings[0].id).toBe('integration-least-privilege-inaccessible');
    expect(r.findings[0].inconclusive).toBe(true);
  });

  it('is inconclusive, not passed, when permissions cannot be queried', async () => {
    const r = await check.run(makeCtx({ users: SVC, psaThrow: true }));
    expect(r.findings[0].id).toBe('integration-least-privilege-permissions-inaccessible');
    expect(r.findings[0].inconclusive).toBe(true);
    expect(r.findings.some((f) => f.passed)).toBe(false);
  });
});

describe('IntegrationLeastPrivilegeCheck — dormancy and protocol', () => {
  const check = new IntegrationLeastPrivilegeCheck();
  const old = new Date(Date.now() - 200 * 86_400_000).toISOString();

  const dormantUser = [{
    Id: '005a', Username: 'svc.api@acme.com',
    Profile: { Name: 'Integration', UserLicense: { Name: 'Salesforce' } },
    LastLoginDate: old, CreatedDate: '2020-01-01T00:00:00.000Z',
  }];

  it('rates a dormant account holding an escalation permission HIGH', async () => {
    const r = await check.run(makeCtx({ users: dormantUser, psa: [psa({ PermissionsAuthorApex: true })] }));
    const f = r.findings.find((x) => x.id === 'integration-least-privilege-dormant')!;
    expect(f.riskLevel).toBe('HIGH');
  });

  it('rates a dormant account with only ordinary grants MEDIUM', async () => {
    const r = await check.run(makeCtx({ users: dormantUser, psa: [psa({ PermissionsViewAllUsers: true })] }));
    expect(r.findings.find((x) => x.id === 'integration-least-privilege-dormant')!.riskLevel).toBe('MEDIUM');
  });

  it('does not report a recently used account as dormant', async () => {
    const r = await check.run(makeCtx({ users: SVC, psa: [psa({ PermissionsAuthorApex: true })] }));
    expect(r.findings.map((f) => f.id)).not.toContain('integration-least-privilege-dormant');
  });

  // Rewritten from "notes that an API-only account cannot be exercising a Setup permission".
  // That claim was false: every escalation permission in this finding is exercisable over the API
  // (Author Apex via Metadata API deploys and anonymous Apex, Manage Users via User DML, and so
  // on). The note now says what api-only actually establishes — no human is driving these through
  // the UI — and must not claim the permission cannot be exercised.
  const apiOnlyCtx = () => makeCtx({
    users: SVC,
    psa: [psa({
      PermissionsCustomizeApplication: true,
      PermissionsDataExport: true,
      PermissionsPasswordNeverExpires: true,
    })],
    logins: [{ UserId: '005a', Application: 'Data Loader Bulk', ApiType: 'SOAP Partner', logins: 9 }],
  });

  it('notes on an API-only account that no human is exercising the escalation permissions through the UI', async () => {
    const r = await check.run(apiOnlyCtx());
    const f = r.findings.find((x) => x.id === 'integration-least-privilege-escalation-permissions')!;
    expect(f.detail).toContain('no interactive login');
    expect(f.detail).toContain('not evidence they are unused');
    expect(f.detail).not.toContain('cannot be being exercised');
  });

  // The note fires when at least one matched account is api-only, but the finding can list several
  // accounts holding the same permission. It must not then claim, about the whole finding, something
  // true of only the api-only account — a human may well be exercising Author Apex through the UI
  // on one of the others.
  it('scopes the api-only note to the account that is api-only, not to every account the finding lists', async () => {
    const users = [
      SVC[0],
      {
        Id: '005b', Username: 'integration.svc@acme.com',
        Profile: { Name: 'Integration', UserLicense: { Name: 'Salesforce' } },
        LastLoginDate: '2026-08-25T00:00:00.000Z', CreatedDate: '2020-01-01T00:00:00.000Z',
      },
    ];
    const r = await check.run(makeCtx({
      users,
      psa: [
        psa({ PermissionsAuthorApex: true }),
        {
          AssigneeId: '005b', PermissionSetId: '0PS2',
          PermissionSet: { Name: 'Integration PS 2', IsOwnedByProfile: false, ...NO_PERMS, PermissionsAuthorApex: true },
        },
      ],
      // 005a is api-only (SOAP/Bulk only); 005b has an interactive browser login in the window.
      logins: [
        { UserId: '005a', Application: 'Data Loader Bulk', ApiType: 'SOAP Partner', logins: 9 },
        { UserId: '005b', Application: 'Browser', ApiType: null, logins: 5 },
      ],
    }));
    const f = r.findings.find((x) => x.id === 'integration-least-privilege-escalation-permissions')!;
    expect(f.affectedItems).toHaveLength(2);
    expect(f.detail).toContain('the permissions that account holds through the UI');
    expect(f.detail).not.toContain('no person is exercising these permissions through the UI');
  });

  it('scopes the api-only note to the escalation finding, never to data or hygiene', async () => {
    const r = await check.run(apiOnlyCtx());
    const data = r.findings.find((x) => x.id === 'integration-least-privilege-data-permissions')!;
    const hygiene = r.findings.find((x) => x.id === 'integration-least-privilege-hygiene')!;
    expect(data.detail).not.toContain('no interactive login');
    expect(hygiene.detail).not.toContain('no interactive login');
  });

  it('describes a dormant account\'s risk as unlikely to be noticed, not "missed while it is used"', async () => {
    const r = await check.run(makeCtx({ users: dormantUser, psa: [psa({ PermissionsAuthorApex: true })] }));
    const f = r.findings.find((x) => x.id === 'integration-least-privilege-dormant')!;
    expect(f.detail).toContain('unlikely to be noticed');
    expect(f.detail).not.toContain('missed while it is used');
  });
});

const objPerm = (obj: string) => ({
  ParentId: '0PS1', SobjectType: obj,
  PermissionsCreate: true, PermissionsEdit: true, PermissionsDelete: false,
});

describe('IntegrationLeastPrivilegeCheck — write evidence', () => {
  const check = new IntegrationLeastPrivilegeCheck();

  it('reports an object the account is granted write on and has never written to', async () => {
    const r = await check.run(makeCtx({ users: SVC, psa: [psa()], objPerms: [objPerm('Opportunity')] }));
    const f = r.findings.find((x) => x.id === 'integration-least-privilege-unused-write-objects')!;
    expect(f.affectedItems!.some((i) => i.label.includes('Opportunity'))).toBe(true);
  });

  // The guard against the worse error. An ETL that only upserts never appears in CreatedById, so a
  // check probing creation alone would accuse it of holding a write grant it exercises nightly.
  it('does NOT report an object the account only ever modified, never created', async () => {
    const r = await check.run(makeCtx({
      users: SVC, psa: [psa()], objPerms: [objPerm('Account')],
      writes: { Account: { CreatedById: [], LastModifiedById: [{ LastModifiedById: '005a', c: 4200 }] } },
    }));
    expect(r.findings.map((f) => f.id)).not.toContain('integration-least-privilege-unused-write-objects');
  });

  it('does NOT report an object the account created records in', async () => {
    const r = await check.run(makeCtx({
      users: SVC, psa: [psa()], objPerms: [objPerm('Account')],
      writes: { Account: { CreatedById: [{ CreatedById: '005a', c: 12 }] } },
    }));
    expect(r.findings.map((f) => f.id)).not.toContain('integration-least-privilege-unused-write-objects');
  });

  // Controller ruling R5: unprobed-only (no unused objects, at least one unprobed) must be
  // inconclusive, not a graded MEDIUM finding titled "0 object(s)...".
  it('lists an object whose probe throws as unprobed, never as unused, and is inconclusive when nothing else is unused', async () => {
    const r = await check.run(makeCtx({
      users: SVC, psa: [psa()], objPerms: [objPerm('Account')],
      writes: { Account: 'THROW' },
    }));
    const f = r.findings.find((x) => x.id === 'integration-least-privilege-unused-write-objects');
    expect(f?.affectedItems?.some((i) => i.label.includes('Account') && i.note?.includes('not probed'))).toBe(true);
    expect(f?.affectedItems?.some((i) => i.label.includes('Account') && i.note?.includes('never written'))).toBeFalsy();
    expect(f?.inconclusive).toBe(true);
    expect(f?.title).not.toContain('0 object(s)');
  });

  // C1: the probe runs with sharing enforced as the audit user. Without View All Data an object
  // whose records are simply invisible returns zero rows, which is indistinguishable from "never
  // written" — so no object may be reported as unused on such a run.
  it('reports every object as unprobed, never as unused, when the audit user lacks View All Data', async () => {
    const r = await check.run(makeCtx({
      users: SVC, psa: [psa()], objPerms: [objPerm('Opportunity')],
      auditUserSeesAllRecords: false,
    }));
    const f = r.findings.find((x) => x.id === 'integration-least-privilege-unused-write-objects')!;
    expect(f.inconclusive).toBe(true);
    expect(f.affectedItems!.some((i) => i.note?.includes('never written'))).toBe(false);
    expect(f.affectedItems![0].note).toContain('View All Data');
    expect(f.detail).toContain('does not hold View All Data');
  });

  it('does not run the record probes at all when the audit user lacks View All Data', async () => {
    const ctx = makeCtx({
      users: SVC, psa: [psa()], objPerms: [objPerm('Opportunity')],
      auditUserSeesAllRecords: false,
    });
    await check.run(ctx);
    const probes = ((ctx.soql.queryAll as unknown) as jest.Mock).mock.calls
      .map((c) => c[0] as string)
      .filter((s) => /FROM Opportunity WHERE CreatedById/.test(s));
    expect(probes).toEqual([]);
  });

  it('draws no conclusion when the running audit user cannot be identified', async () => {
    const r = await check.run(makeCtx({
      users: SVC, psa: [psa()], objPerms: [objPerm('Opportunity')],
      auditUser: 'THROW',
    }));
    const f = r.findings.find((x) => x.id === 'integration-least-privilege-unused-write-objects')!;
    expect(f.inconclusive).toBe(true);
    expect(f.affectedItems![0].note).toContain('could not be established');
  });

  it('draws no conclusion when the identity response carries no usable user id', async () => {
    const r = await check.run(makeCtx({
      users: SVC, psa: [psa()], objPerms: [objPerm('Opportunity')],
      auditUser: 'NO_ID',
    }));
    expect(r.findings.find((x) => x.id === 'integration-least-privilege-unused-write-objects')!.inconclusive).toBe(true);
  });

  it('does not interpolate an unexpected identity value into a query', async () => {
    const ctx = makeCtx({
      users: SVC, psa: [psa()], objPerms: [objPerm('Opportunity')],
      auditUser: "005' OR Id != null--",
    });
    await check.run(ctx);
    const sqls = ((ctx.soql.queryAll as unknown) as jest.Mock).mock.calls.map((c) => c[0] as string);
    expect(sqls.some((s) => s.includes('OR Id != null'))).toBe(false);
  });

  it('names the View All Data dependency in the write-evidence finding', async () => {
    const r = await check.run(makeCtx({ users: SVC, psa: [psa()], objPerms: [objPerm('Opportunity')] }));
    const f = r.findings.find((x) => x.id === 'integration-least-privilege-unused-write-objects')!;
    expect(f.detail).toContain('View All Data');
    expect(f.detail).toContain('sharing enforced');
  });

  // I1: "remove the grant" is destructive advice when the grant is a shared profile or an org-wide
  // permission set, so each unused object has to name where the grant comes from and how widely
  // that grant is held.
  it('names the granting permission set on each unused object', async () => {
    const r = await check.run(makeCtx({ users: SVC, psa: [psa()], objPerms: [objPerm('Opportunity')] }));
    const item = r.findings.find((x) => x.id === 'integration-least-privilege-unused-write-objects')!.affectedItems![0];
    expect(item.note).toContain('via permission set Integration PS');
  });

  // A profile-owned permission set's Name is Salesforce's autogenerated internal string
  // (id-shaped, not a label a real org would ever return for a profile), so the fixture uses one —
  // naming that string in the finding would tell a reader nothing. The grant path must instead use
  // the assignee's own profile name, already carried on the resolved account.
  it('names the granting profile using the assignee\'s profile name, not the autogenerated permission-set name', async () => {
    const r = await check.run(makeCtx({
      users: SVC,
      psa: [psa({ IsOwnedByProfile: true, Name: 'X00e5w000001AbCd' })],
      objPerms: [objPerm('Opportunity')],
    }));
    const item = r.findings.find((x) => x.id === 'integration-least-privilege-unused-write-objects')!.affectedItems![0];
    expect(item.note).toContain('via profile Integration');
    expect(item.note).not.toContain('X00e5w000001AbCd');
  });

  it('warns on the item when the granting set is assigned outside the integration set', async () => {
    const r = await check.run(makeCtx({
      users: SVC, psa: [psa()], objPerms: [objPerm('Opportunity')],
      sharedAssignments: [{ PermissionSetId: '0PS1', c: 1204 }],
    }));
    const f = r.findings.find((x) => x.id === 'integration-least-privilege-unused-write-objects')!;
    expect(f.affectedItems![0].note).toContain('1204 account(s) outside this integration set');
    expect(f.remediation).toContain('assigned outside this integration set');
    expect(f.remediation).not.toMatch(/^Remove /);
  });

  it('says the assignment breadth is unknown rather than implying the grant is exclusive', async () => {
    const r = await check.run(makeCtx({
      users: SVC, psa: [psa()], objPerms: [objPerm('Opportunity')],
      sharedAssignments: 'THROW',
    }));
    const item = r.findings.find((x) => x.id === 'integration-least-privilege-unused-write-objects')!.affectedItems![0];
    expect(item.note).toContain('could not be established');
  });

  it('names objects dropped by the query budget rather than truncating silently', async () => {
    const many = Array.from({ length: 40 }, (_, i) => objPerm(`Obj${i}__c`));
    const r = await check.run(makeCtx({ users: SVC, psa: [psa()], objPerms: many }));
    const f = r.findings.find((x) => x.id === 'integration-least-privilege-unused-write-objects')!;
    expect(f.detail).toContain('not probed');
  });

  // M1: with more objects than the display cap, a genuine probe failure used to be ordered behind
  // budget-skipped objects and pushed out of the visible list while still counted in the title.
  it('shows probe failures ahead of budget-skipped objects and counts both separately', async () => {
    const many = Array.from({ length: 40 }, (_, i) => objPerm(`Obj${i}__c`));
    const r = await check.run(makeCtx({
      users: SVC, psa: [psa()], objPerms: many,
      writes: { Obj0__c: 'THROW' },
    }));
    const f = r.findings.find((x) => x.id === 'integration-least-privilege-unused-write-objects')!;
    const unprobedItems = f.affectedItems!.filter((i) => i.note?.startsWith('not probed'));
    expect(unprobedItems[0].label).toBe('Obj0__c');
    expect(unprobedItems[0].note).toContain('record-count query failed');
    expect(f.detail).toContain('1 object(s) were not probed because the record-count query failed');
    expect(f.detail).toContain('10 object(s) were not probed for budget');
  });

  it('suppresses the finding when ObjectPermissions is unreadable, rather than passing', async () => {
    const r = await check.run(makeCtx({ users: SVC, psa: [psa()], objPermsThrow: true }));
    expect(r.findings.map((f) => f.id)).not.toContain('integration-least-privilege-unused-write-objects');
    expect(r.findings.some((f) => f.passed)).toBe(false);
  });

  it('discloses the ObjectPermissions failure as an inconclusive finding, even with no structural finding alongside it', async () => {
    const r = await check.run(makeCtx({ users: SVC, psa: [psa()], objPermsThrow: true }));
    const f = r.findings.find((x) => x.id === 'integration-least-privilege-object-permissions-inaccessible');
    expect(f).toBeDefined();
    expect(f!.inconclusive).toBe(true);
    expect(r.findings.some((x) => x.passed)).toBe(false);
  });

  it('discloses the ObjectPermissions failure alongside a structural finding, not in place of it', async () => {
    const r = await check.run(makeCtx({
      users: SVC, psa: [psa({ PermissionsAuthorApex: true })], objPermsThrow: true,
    }));
    expect(r.findings.map((f) => f.id)).toContain('integration-least-privilege-object-permissions-inaccessible');
    expect(r.findings.map((f) => f.id)).toContain('integration-least-privilege-escalation-permissions');
    const f = r.findings.find((x) => x.id === 'integration-least-privilege-object-permissions-inaccessible')!;
    expect(f.inconclusive).toBe(true);
    expect(r.findings.some((x) => x.passed)).toBe(false);
  });
});

describe('IntegrationLeastPrivilegeCheck — the passing path', () => {
  const check = new IntegrationLeastPrivilegeCheck();

  it('passes with -ok when accounts exist and hold nothing surplus', async () => {
    const r = await check.run(makeCtx({ users: SVC, psa: [psa()] }));
    expect(r.findings.map((f) => f.id)).toEqual(['integration-least-privilege-ok']);
    expect(r.findings[0].passed).toBe(true);
  });

  it('names the read blind spot in the passing finding', async () => {
    const r = await check.run(makeCtx({ users: SVC, psa: [psa()] }));
    expect(r.findings[0].detail).toContain('Read grant');
    expect(r.findings[0].detail).toContain('sf audit apps');
  });

  it('discloses a degraded signal in the passing finding', async () => {
    const r = await check.run(makeCtx({ users: SVC, psa: [psa()], loginsThrow: true }));
    expect(r.findings[0].detail).toContain('api-only-login');
  });

  // M4: the qualification count was hard-coded to "Two" regardless of how many signals degraded.
  it('agrees in number with how many signals actually degraded', async () => {
    const one = await check.run(makeCtx({ users: SVC, psa: [psa()] }));
    expect(one.findings[0].detail).toContain('One qualification:');

    const two = await check.run(makeCtx({ users: SVC, psa: [psa()], loginsThrow: true }));
    expect(two.findings[0].detail).toContain('2 qualifications:');
  });

  it('names the record-visibility limit of the write probe in the passing finding', async () => {
    const r = await check.run(makeCtx({ users: SVC, psa: [psa()] }));
    expect(r.findings[0].detail).toContain('View All Data');
  });

  it('discloses a truncated candidate set in the passing finding', async () => {
    const many = Array.from({ length: 200 }, (_, i) => ({
      Id: `005x${String(i).padStart(11, '0')}`, Username: `integration${i}@acme.com`,
      Profile: { Name: 'Integration', UserLicense: { Name: 'Salesforce' } },
      LastLoginDate: '2026-08-25T00:00:00.000Z', CreatedDate: '2020-01-01T00:00:00.000Z',
    }));
    const r = await check.run(makeCtx({ users: many, psa: [] }));
    expect(r.findings[0].id).toBe('integration-least-privilege-ok');
    expect(r.findings[0].detail).toContain('truncated');
  });
});

describe('IntegrationLeastPrivilegeCheck — the -none finding', () => {
  const check = new IntegrationLeastPrivilegeCheck();

  // C3: connected-app-run-as is never gathered (the resolver reports it degraded on every run), so
  // listing it among the signals that were matched claimed an evaluation that never happened — on
  // the finding most likely to be read as "you have no integration accounts".
  it('does not claim the unimplemented connected-app run-as signal was evaluated', async () => {
    const r = await check.run(makeCtx({ users: [] }));
    const none = r.findings.find((f) => f.id === 'integration-least-privilege-none')!;
    expect(none.detail).not.toContain('connected-app run-as user');
  });

  it('discloses the connected-app-run-as gap on the none finding', async () => {
    const r = await check.run(makeCtx({ users: [] }));
    const none = r.findings.find((f) => f.id === 'integration-least-privilege-none')!;
    expect(none.detail).toContain('connected-app-run-as');
    expect(none.detail).toContain('could not be gathered');
  });
});
