export interface CheckMeta {
  /** Remediation effort tier: quick = ≤1 day, moderate = days, project = weeks. */
  effort: 'quick' | 'moderate' | 'project';
  /** One-sentence abuse/incident narrative for standalone (non-chained) top-N findings. */
  impact: string;
}

export const CHECK_META: Record<string, CheckMeta> = {
  'users-and-admins':        { effort: 'moderate', impact: 'Over-privileged admins mean one compromised account can read, alter, or export the entire org’s data.' },
  'permissions':             { effort: 'moderate', impact: 'Permission-set sprawl widens the blast radius of any single account takeover.' },
  'inactive-users':          { effort: 'quick',    impact: 'Dormant but active accounts are unmonitored entry points attackers reuse without raising suspicion.' },
  'login-session':           { effort: 'quick',    impact: 'Weak session settings let a stolen session token stay valid long enough to be replayed.' },
  'ip-restrictions':         { effort: 'moderate', impact: 'Without IP restrictions, stolen admin credentials work from anywhere in the world.' },
  'password-session-policy': { effort: 'quick',    impact: 'Weak password and session policy makes credential guessing and session hijacking far easier.' },
  'field-level-security':    { effort: 'moderate', impact: 'Sensitive fields (SSN, card, tax id) exposed to broad permission sets leak PII to users who shouldn’t see it.' },
  'sharing-model':           { effort: 'project',  impact: 'Loose org-wide defaults expose records org-wide; any internal user can read data meant to be private.' },
  'public-group-sharing':    { effort: 'moderate', impact: 'Sharing rules granting “All Internal Users” turn a low-privilege account into a path to sensitive records.' },
  'guest-user-access':       { effort: 'moderate', impact: 'Object access granted to unauthenticated guests lets anonymous web visitors read or modify records.' },
  'apex-sharing':            { effort: 'project',  impact: 'without-sharing Apex bypasses record access, letting low-privilege or guest users reach data they can’t otherwise see.' },
  'flows-without-sharing':   { effort: 'moderate', impact: 'System-context flows without sharing run with elevated rights, exposing records to whoever triggers them.' },
  'connected-apps':          { effort: 'moderate', impact: 'Connected apps not admin-restricted let any user authorize a third-party app to act on org data.' },
  'remote-sites':            { effort: 'quick',    impact: 'Permissive remote sites allow Apex callouts to attacker-controlled endpoints (SSRF and data exfiltration).' },
  'csp-trusted-sites':       { effort: 'quick',    impact: 'Insecure HTTP CSP entries allow mixed-content loading and man-in-the-middle script injection.' },
  'named-credentials':       { effort: 'quick',    impact: 'Unmanaged callout endpoints can send org data to unintended or attacker-controlled destinations.' },
  'hardcoded-credentials':   { effort: 'moderate', impact: 'Secrets embedded in Apex can be read by anyone with code access and reused to reach connected systems.' },
  'custom-settings':         { effort: 'quick',    impact: 'Credential-like custom settings may store secrets readable by users who can query them.' },
  'health-check':            { effort: 'moderate', impact: 'Unaddressed Health Check high-risk settings are documented, exploitable misconfigurations.' },
  'audit-trail':             { effort: 'quick',    impact: 'Without reviewing the audit trail, malicious permission changes and Login-As abuse go undetected.' },
  'code-security':           { effort: 'project',  impact: 'Low Apex test coverage and injection-prone code hide exploitable vulnerabilities behind untested paths.' },
  'api-limits':              { effort: 'quick',    impact: 'API exhaustion, deliberate or accidental, can cause denial of service for integrations and users.' },
  'scheduled-apex':          { effort: 'quick',    impact: 'Unreviewed scheduled jobs can run unauthorized logic on a recurring basis unnoticed.' },
  'standard-profiles':       { effort: 'moderate', impact: 'Standard profiles grant broad default permissions; users on them often have more access than intended.' },
  'sso-enforcement':         { effort: 'project',  impact: 'Without enforced SSO, username/password logins bypass your identity provider’s MFA and conditional access.' },
  'mfa-enforcement':         { effort: 'quick',    impact: 'Portal/external users without MFA let a stolen password reach customer or partner data directly.' },
  'api-client-permission':   { effort: 'quick',    impact: '“Use Any API Client” bypasses API Access Control, letting a user reach the org from any tool.' },
  'integration-users':       { effort: 'moderate', impact: 'Over-privileged service accounts are prime targets: one stolen key grants broad, unattended access.' },
  'content-links':           { effort: 'quick',    impact: 'Public file links without expiry or password leak documents to anyone who finds the URL.' },
  'field-history-tracking':  { effort: 'quick',    impact: 'Without field history, tampering with sensitive records can’t be reconstructed after an incident.' },
  'data-classification':     { effort: 'moderate', impact: 'Unclassified sensitive data can’t be protected or encrypted consistently, increasing exposure.' },
  'deployment-identity':     { effort: 'moderate', impact: 'No controlled deployment identity means malicious metadata changes blend in with normal admin activity.' },
  'apex-logging':            { effort: 'moderate', impact: 'Missing logging leaves no trail to detect or investigate abuse of Apex execution.' },
  'event-monitoring':        { effort: 'moderate', impact: 'Without Event Monitoring, data exfiltration and abuse leave no detailed forensic record.' },
  'siem-integration':        { effort: 'project',  impact: 'No SIEM forwarding means security events are never correlated or alerted on outside the org.' },
  'apex-crud-fls':           { effort: 'project',  impact: 'Apex skipping CRUD/FLS checks lets callers read or write records and fields they have no rights to.' },
  'apex-rest-endpoint':      { effort: 'project',  impact: 'without-sharing @RestResource endpoints expose records to REST callers without record-level access control.' },
  'visualforce-xss':         { effort: 'moderate', impact: 'Unescaped Visualforce merge fields let attackers inject scripts that run in victims’ sessions.' },
  'certificate-expiry':      { effort: 'quick',    impact: 'An expired certificate breaks integrations or, if ignored, invites insecure fallback.' },
  'installed-packages':      { effort: 'moderate', impact: 'Unmanaged or beta packages in production can carry unvetted code with broad org access.' },
  'trusted-ip-ranges':       { effort: 'quick',    impact: 'Overly broad trusted IP ranges silently exempt large networks from MFA.' },
  'anonymous-apex-audit':    { effort: 'quick',    impact: 'Anonymous Apex execution in production can run arbitrary privileged code leaving little trace.' },
  'debug-log-access':        { effort: 'quick',    impact: 'Active high-detail debug traces capture sensitive field values readable by anyone with log access.' },
  'connected-app-inactivity':{ effort: 'quick',    impact: 'Stale connected apps remain authorized attack surface long after they’re abandoned.' },
  'my-domain-login-policy':  { effort: 'quick',    impact: 'Allowing login.salesforce.com login bypasses My Domain SSO enforcement.' },
  'high-assurance-session':  { effort: 'moderate', impact: 'Admin-capable apps without short or high-assurance sessions let a hijacked session retain elevated rights.' },
  'enhanced-domains':        { effort: 'moderate', impact: 'Without Enhanced Domains, cross-org cookie leakage and URL spoofing become possible.' },
  'internal-user-mfa':       { effort: 'quick',    impact: 'A stolen or guessed admin password grants full org access with no second factor to stop it.' },
  'mfa-registration':        { effort: 'quick',    impact: 'Users with no registered MFA method are effectively single-factor and easily phished.' },
  'mfa-method-strength':     { effort: 'moderate', impact: 'Weak MFA methods such as SMS are bypassable via SIM-swap and real-time phishing.' },
  'release-updates':         { effort: 'quick',    impact: 'Ignored release updates leave known-deprecated, sometimes insecure behavior active past its deadline.' },
  'legacy-api-version':      { effort: 'moderate', impact: 'Apex on old API versions and SOAP remote sites carry deprecated, less-secure behavior.' },
  'connected-app-scope':     { effort: 'moderate', impact: 'Full-scope OAuth grants and infinite refresh tokens make a single leaked token catastrophic.' },
  'transaction-security-policy': { effort: 'moderate', impact: 'Without transaction security policies, automated threats like bulk export or anomalous logins go unblocked.' },
  'failed-login-detection':  { effort: 'quick',    impact: 'No brute-force detection means credential-stuffing campaigns run unnoticed until they succeed.' },
  'experience-cloud-site':   { effort: 'moderate', impact: 'Self-registration on live sites lets attackers create their own accounts to probe guest-accessible data.' },
  'custom-labels-credential':{ effort: 'quick',    impact: 'Credentials in custom labels are globally readable by all authenticated users via merge fields.' },
  'report-folder-access':    { effort: 'quick',    impact: 'Public report folders let any authenticated user view all reports and the data behind them: mass exfiltration.' },
  'escalation-perms':        { effort: 'moderate', impact: 'Lateral-movement permissions let a compromised account grant itself more access and persist.' },
  'cors-allowlist':          { effort: 'quick',    impact: 'Wildcard CORS origins let malicious sites make authenticated browser requests against the org.' },
  'guest-executable-apex':   { effort: 'project',  impact: 'Unauthenticated web users can execute Apex that bypasses sharing: bulk record exfiltration without login.' },
  'email-security':          { effort: 'quick',    impact: 'Unauthenticated inbound email services and all-profile send-as addresses let attackers trigger Apex or spoof internal senders.' },
  'outbound-messages':       { effort: 'quick',    impact: 'Outbound messages can ship a live session ID to external endpoints over cleartext: a direct session-hijack and exfiltration path.' },
  'public-content-exposure': { effort: 'quick',    impact: 'Documents marked externally available and public static resources are retrievable without authentication by anyone with the URL.' },
  'privileged-access':       { effort: 'moderate', impact: 'Shadow admins hold full org control outside the admin profile, so a single takeover bypasses admin-focused monitoring and owns everything.' },
  'separation-of-duties':    { effort: 'moderate', impact: 'A single user holding a toxic permission combination can self-escalate, commit fraud, or tamper undetected with no second party to stop them.' },
  'guest-object-exposure':   { effort: 'moderate', impact: 'Grades guest-readable objects by ACTUAL UI-API reachability: objects the UI API models are bulk-readable unauthenticated via GraphQL (CRITICAL, incl. guest-owned records under a Private OWD, enabling mass PII exfiltration without login); objects readable only in the sharing model but not UI-API-modelled (Calendar, AuthSession, etc.) are separated as MEDIUM defense-in-depth, with UserRecordAccess as ground-truth read confirmation.' },
  'guest-site-options':      { effort: 'quick',    impact: 'Guest file access and member visibility let unauthenticated visitors download public files and enumerate site members.' },
  'threat-detection':        { effort: 'moderate', impact: 'Without Guest User Anomaly storage, malicious guest bulk-reads are never flagged and cannot be reconstructed after the fact.' },
  'guest-record-access-policy': { effort: 'quick', impact: 'Without "Secure guest user record access" enforced, guests own the records they submit and can read them under a Private OWD, turning a public form into an unauthenticated bulk-read surface.' },
  'guest-traffic-anomaly':   { effort: 'moderate', impact: 'Guest requests from anonymizer/hosting IPs, single-IP bursts, and GraphQL totalCount sweeps are the live signatures of scraping and pre-exfiltration recon — unmonitored, they only surface after data is gone.' },
  'login-access-policy':     { effort: 'moderate', impact: 'Delegated admins and "log in as any user" let accounts impersonate others and self-escalate, bypassing normal credentials and admin-focused monitoring.' },
  'data-export-access':      { effort: 'quick',    impact: 'Weekly Data Export or API access with View/Modify All is a one-step, org-wide exfiltration capability in the wrong hands.' },
  'classic-sites':           { effort: 'moderate', impact: 'Active classic Visualforce sites expose a second unauthenticated guest surface that the Experience Cloud checks never inspect.' },
  'auth-providers':          { effort: 'moderate', impact: 'Unvetted social/SAML identity providers with just-in-time provisioning can let attackers federate in or auto-create over-privileged users.' },
  'guest-api-access':        { effort: 'quick',    impact: 'A guest user with API access can drive the raw REST/Bulk API, turning readable objects into scriptable mass extraction (and Hard Delete into irreversible destruction) without login.' },
  'external-credentials':    { effort: 'moderate', impact: 'Callouts with no or custom authentication can be spoofed or leak a static secret, exposing the integrated system and the data crossing it.' },
  'login-anomaly':           { effort: 'quick',    impact: 'An account logging in from many distinct IPs signals credential sharing or compromise; caught late, it means an attacker already has a working session.' },
  'session-hardening':       { effort: 'quick',    impact: 'Weak clickjack/CSRF/session-lock/XSS settings let attackers hijack authenticated sessions via framing, forged requests, or injected script.' },
  'encryption-coverage':     { effort: 'moderate', impact: 'Fields labelled PII/PHI but stored in plaintext are unprotected at rest and on export — the sensitivity is known, the protection is missing.' },
  'experience-csp':          { effort: 'moderate', impact: 'Relaxed CSP or disabled Lightning Web Security on a public site lets injected/third-party scripts run against unauthenticated visitors.' },
  'sandbox-data-masking':    { effort: 'moderate', impact: 'Unmasked production PII/PHI copied into a sandbox spreads sensitive data into a lower-trust environment with broader access and weaker monitoring.' },
};

export function getCheckMeta(id: string): CheckMeta | undefined {
  return CHECK_META[id];
}
