import type { ControlDef } from '../types.js';

const V = 'SOC 2 (2017 TSC)';

export const SOC2_CONTROLS: ControlDef[] = [
  { id: 'SOC2-CC6.1', framework: 'SOC2', version: V, title: 'Logical access controls',
    requirement: 'The entity implements logical access security measures to protect against unauthorized access to information assets.',
    sourceRef: 'SOC 2 (2017 TSC), CC6.1', verified: false },
  { id: 'SOC2-CC6.2', framework: 'SOC2', version: V, title: 'User registration and authorization',
    requirement: 'Prior to issuing credentials, the entity registers and authorizes new users; access is removed when no longer required.',
    sourceRef: 'SOC 2 (2017 TSC), CC6.2', verified: false },
  { id: 'SOC2-CC6.3', framework: 'SOC2', version: V, title: 'Role-based access and least privilege',
    requirement: 'Access to information assets is granted based on roles and least privilege, and is reviewed and modified as roles change.',
    sourceRef: 'SOC 2 (2017 TSC), CC6.3', verified: false },
  { id: 'SOC2-CC6.4', framework: 'SOC2', version: V, title: 'Access restrictions for sensitive resources',
    requirement: 'The entity restricts access to information assets to authorized personnel, including network and remote-access boundaries.',
    sourceRef: 'SOC 2 (2017 TSC), CC6.4', verified: false },
  { id: 'SOC2-CC6.6', framework: 'SOC2', version: V, title: 'Boundary protection against external threats',
    requirement: 'The entity implements controls to protect against threats from sources outside its system boundaries (e.g. external app access).',
    sourceRef: 'SOC 2 (2017 TSC), CC6.6', verified: false },
  { id: 'SOC2-CC6.7', framework: 'SOC2', version: V, title: 'Restricting the transmission of information',
    requirement: 'The entity restricts the transmission, movement, and storage of information to authorized users and protects it in transit.',
    sourceRef: 'SOC 2 (2017 TSC), CC6.7', verified: false },
  { id: 'SOC2-CC7.1', framework: 'SOC2', version: V, title: 'Detection of configuration changes and vulnerabilities',
    requirement: 'The entity uses detection measures to identify configuration changes and vulnerabilities that could introduce new risks.',
    sourceRef: 'SOC 2 (2017 TSC), CC7.1', verified: false },
  { id: 'SOC2-CC7.2', framework: 'SOC2', version: V, title: 'Monitoring for anomalies and security events',
    requirement: 'The entity monitors system components for anomalies and security events indicative of malicious acts or errors.',
    sourceRef: 'SOC 2 (2017 TSC), CC7.2', verified: false },
  { id: 'SOC2-CC8.1', framework: 'SOC2', version: V, title: 'Change management',
    requirement: 'Changes to infrastructure, data, and software are authorized, designed, tested, and deployed under a controlled process.',
    sourceRef: 'SOC 2 (2017 TSC), CC8.1', verified: false },
  { id: 'SOC2-CC9.1', framework: 'SOC2', version: V, title: 'Risk mitigation for business disruptions',
    requirement: 'The entity identifies and mitigates risks arising from potential business disruptions, including resource/capacity limits.',
    sourceRef: 'SOC 2 (2017 TSC), CC9.1', verified: false },
  { id: 'SOC2-CC9.2', framework: 'SOC2', version: V, title: 'Vendor and third-party risk management',
    requirement: 'The entity assesses and manages risks associated with vendors and third-party components (e.g. installed packages).',
    sourceRef: 'SOC 2 (2017 TSC), CC9.2', verified: false },
];
